---
- name: "Creates backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "List Dir"
  shell: |
    ls
    ls /home/circleci/project/.circleci/ansible/roles/deploy/files/

- name: "Unarchive backend files"
  become: true
  become_method: sudo
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app
    remote_src: yes

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend-app
    npm i

- name: "Executing Node app with PM2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure PM2 to Start Service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd-u ubuntu --hp /home/ubuntu
